### ISSUE TITLE
Decompression crashes

### ISSUE THREAD

**Issue by rwhitworth** [andyherbert/lz1#1]
I ran [afl-fuzz](http://lcamtuf.coredump.cx/afl/) on the decompression code and came up with 10 input files that cause unique crashes.  I have not spent time determining the root cause.  The input files are attached in case you wish to inspect.

[crashes.zip](https://github.com/andyherbert/lz1/files/404834/crashes.zip)

**Comment by andyherbert** [comment]
The code is meant to be instructional, and lacks boundary and error checks for the sake of brevity.
